### ISSUE TITLE
Test Suite fails if port 8080 is bound

### ISSUE THREAD

**Issue by keep94** [wavefrontHQ/wavefront-sdk-go#102]
If port 8080 is bound by an ordinary web app, the test suite of this module fails.

Expected behavior: The test suite should pass even if port 8080 is bound.

**Comment by oppegard** [comment]
@keep94 was this not fixed in #105, and this issue should be closed?

**Comment by oppegard** [comment]
@keep94 FYI, Github can automatically close issues by linking a PR to it through a commit message. For example, if the commit message includes text that says:

> Fixes #102

For more info on the syntax Github will handle, check out https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by keep94** [comment]
fixed in #105
