### ISSUE TITLE
Document internal SDK metrics

### ISSUE THREAD

**Issue by oppegard** [wavefrontHQ/wavefront-sdk-go#106]
(split out from #101)

Document internal SDK metrics (`~sdk.` prefix) in the README with a new section titled "Monitor the SDK." Certain ones from the deleted Proxy Sender are no longer valid and are gone altogether. For reference on an existing way we document internal metrics for the Java SDK, see https://github.com/wavefrontHQ/wavefront-sdk-doc-sources/blob/master/java/internalmetrics.md.

Make it known that the metrics will have one of two possible prefixes, depending on direct ingestion or proxy ingestion:
- `~sdk.go.core.sender.direct`
- `~sdk.go.core.sender.proxy`

**Comment by LukeWinikates** [comment]
@oppegard @keep94 do you think that #107 resolves this issue?
