### ISSUE TITLE
proposal: change FlushIntervalSeconds to time.Duration

### ISSUE THREAD

**Issue by oppegard** [wavefrontHQ/wavefront-sdk-go#121]
I propose switching the [FlushIntervalSeconds](https://github.com/wavefrontHQ/wavefront-sdk-go/blob/04d179534ab98d1bf918d066e4d4ffa2b56f842f/senders/client_factory.go#L48) configuration from an `int` to a `time.Duration`. It improves code expressiveness and sets a precedent for future config options that are durations. The config would be renamed from `FlushIntervalSeconds` to `FlushInterval`.

For an example like this in the stdlib, see `ReverseProxy.FlushInterval`: https://pkg.go.dev/net/http/httputil@go1.19.2#ReverseProxy.

cc @keep94 @LukeWinikates

**Comment by LukeWinikates** [comment]
We added a `FlushInterval` setter that uses `time.Duration`. We haven't deprecated `FlushIntervalSeconds`, although I think it's worth considering it.
