### ISSUE TITLE
Send metrics to WF proxy on tls port

### ISSUE THREAD

**Issue by rohitkgupta** [wavefrontHQ/wavefront-sdk-go#136]
I want to send metrics to WF proxy on tls port(4443). https://docs.vdp.vmware.com/docs/using_kubernetes/monitoring/#wavefront-proxy
I am using wavefrontSender.SendMetric to send metrics to WF proxy and I don’t see any option to pass certificates while initializing the sender.
How to send metrics to WF proxy on tls port(4443)?

**Comment by LukeWinikates** [comment]
Hi @rohitkgupta - there are two parts to the answer:

To use port `4443`, include the port in the URL that you pass to `NewSender`. That would look something like:

```golang
sender, err := wavefront.NewSender("https://localhost:4443")
```

I was surprised to see that we don't have an example in the go docs showing the port number - we should definitely add that. I will create a separate GitHub issue for it.

If you need to provide your own TLS CA, this example from the go docs should help you:
https://pkg.go.dev/github.com/wavefronthq/wavefront-sdk-go@v0.13.0/senders#example-NewSender-Options

I'll go ahead and mark this as closed, but if you have trouble, please reopen this issue.

**Comment by rohitkgupta** [comment]
Thanks @LukeWinikates 
I will try this.
