### ISSUE TITLE
question: why can't we send timestamps with delta counters?

### ISSUE THREAD

**Issue by marcosrmendezthd** [wavefrontHQ/wavefront-sdk-go#3]
we'll be sending a number of metrics and some of them will be delta counters, however the metrics will be batched and won't be realtime. i would expect to be able to send timestamps for the delta counters as well.

**Comment by marcosrmendezthd** [comment]
just reviewed https://docs.wavefront.com/delta_counters.html. this may be as designed. we'll have to think about how we're going to use them.

**Comment by vikramraman** [comment]
@marcosrmendezthd Yes delta counters are aggregated on the server side and the timestamp is assigned at aggregation time. Amongst others, useful in ephemeral scenarios where normal counters would typically reset.
