### ISSUE TITLE
SendDistributions handles granularities in a confusing way

### ISSUE THREAD

**Issue by prydin** [wavefrontHQ/wavefront-sdk-go#33]
The granularities passed to ```SendDistributions()``` are encoded as a ```map[string]bool``` which leads one to believe that setting one of the granularities to ```false``` would exclude it. However, the check is only done on whether the key is present, not the value. So this...

```
var granularities = map[histogram.Granularity]bool{
	histogram.MINUTE: true,
	histogram.HOUR:   false,
	histogram.DAY:    false,
}
```

...actually causes all three granularities to be sent.

**Comment by vikramraman** [comment]
Fixed by #49
