### ISSUE TITLE
cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid

### ISSUE THREAD

**Issue by thespacecowboys45** [wavefrontHQ/wavefront-sdk-go#45]
I did a go-get on this package and got the following errors:

$ go get github.com/wavefronthq/wavefront-sdk-go/senders
# github.com/wavefronthq/wavefront-sdk-go/histogram
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:103:31: cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:120:31: cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:141:31: cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:161:31: cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:178:31: cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:199:31: cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:232:31: cannot use func literal (type func(float64, uint32) bool) as type func(float64, uint64) bool in argument to bin.tdigest.ForEachCentroid
../../../../github.com/wavefronthq/wavefront-sdk-go/histogram/histogram.go:264:44: cannot use h.compression (type uint32) as type float64 in argument to tdigest.Compression

I thought I would check the function declaration to see if the types matched or not:

https://github.com/caio/go-tdigest/blob/master/tdigest.go

It looks like the histogram.go code is passing the wrong types to bin.tdigest.ForEachCentroid and to tdigest.Compression.

**Comment by vikramraman** [comment]
We use an earlier version of t-digest: https://github.com/wavefrontHQ/wavefront-sdk-go/blob/2c5891318fcd83c35c93bba2b411640495473333/go.mod#L6

`go mod init <name>` and `go mod tidy` should fix it for you.

**Comment by xavierba** [comment]
@vikramraman, any plan to update to latest tdigest 3.1.0 ?

**Comment by vikramraman** [comment]
Addressed by #48
