### ISSUE TITLE
pluggable logging interface

### ISSUE THREAD

**Issue by marcosrmendezthd** [wavefrontHQ/wavefront-sdk-go#5]
can we add an option to override logging using log.PrintX functions?

**Comment by vikramraman** [comment]
@marcosrmendezthd Is the ask to suppress log statements emitted by this SDK or to output to a file or such? If the latter you could in your app code do `log.SetOutput(f)` and all log statements from this SDK would be written to a file or such.

**Comment by marcosrmendezthd** [comment]
@vikramraman actually we use a different library for structured logging. this would let us put some context around these log messages, as well as suppress them if needed.

for example, when we start a sender, no metrics have been queued and we hit the flush interval we get a log message "flush error: empty proxy connection". in our case, this is not really an error.

**Comment by vikramraman** [comment]
Thanks for the feedback! Will look into it.

**Comment by vikramraman** [comment]
https://github.com/wavefrontHQ/wavefront-sdk-go/commit/d1e1741a31af0a8e7234cc1515425470ad06e249

Added a log statement upon connecting and there is a log statement if connection is reset. The flush itself only returns an error if it tried to flush the writer. This should prevent irrelevant logging for now. We might consider using glog in the near future and will revisit this then.
