### ISSUE TITLE
ability to modify direct sender client configuration

### ISSUE THREAD

**Issue by marcosrmendezthd** [wavefrontHQ/wavefront-sdk-go#6]
we used internally signed certificates and would like to be able to provide those to the direct sender as well connection timeouts, etc.

**Comment by marcosrmendezthd** [comment]
we probably need similar options on the proxy sender as well. :smile:

**Comment by LukeWinikates** [comment]
I know this is an old issue, but my team has also wanted to experiment with directly configuring the http client and its TLS settings. I think this would be worth doing, especially if we can find a low-ceremony way of passing the http client config options through.

**Comment by LukeWinikates** [comment]
One more note for future readers - since there's only one factory method for connections now, this should be easier than it would have been in 2018 because there's no distinction between direct sender and proxy sender anymore.

**Comment by LukeWinikates** [comment]
@oppegard I think maybe we can mark this one closed now that #122 is merged

**Comment by oppegard** [comment]
Closed by #122
