### ISSUE TITLE
Improve logging details in network connections

### ISSUE THREAD

**Issue by oppegard** [wavefrontHQ/wavefront-sdk-go#63]
Given the following output from the SDK:

```
otel             | 2021/06/16 16:58:42 connected to Wavefront proxy at address: wavefront-proxy:2878
otel             | 2021/06/16 16:58:42 resetting wavefront proxy connection
otel             | 2021/06/16 16:58:42 connected to Wavefront proxy at address: wavefront-proxy:2879
```

It'd be helpful if the line `resetting wavefront proxy connection` included which connection was being reset. In this case it's probably "wavefront-proxy:2879", but just including it in the message would make it clear.

**Comment by LukeWinikates** [comment]
This log message isn't in the codebase anymore - it was part of the TCP handler that could be used to connect to Wavefront proxy instances. I'll close this issue.
