### ISSUE TITLE
Implement Reconnecting TCP Socket to Proxy

### ISSUE THREAD

**Issue by oppegard** [wavefrontHQ/wavefront-sdk-go#68]
It's possible for the SDK to drop data in the following scenario:
1. SDK makes connection to WF proxy
2. Data is sent to WF proxy
3. Proxy disconnects connection due to lack of activity: e.g. no data sent for 10 seconds and Proxy has config of `--listenerIdleConnectionTimeout 10`
4. A small amount of data is sent through SDK, where "small" is 1024-4096 bytes (something less than kernel TCP buffer size). The TCP `net.Conn` write in go does not return an error.
5. If the program using the SDK is quit, the data is never successfully sent to the Proxy.

Resources:
- The wavefront-sdk-java has a [`ReconnectingSocket.java`](https://github.com/wavefrontHQ/wavefront-sdk-java/blob/master/src/main/java/com/wavefront/sdk/common/ReconnectingSocket.java) that specifically handles this scenario.
- [LeanStreams](https://github.com/cloudfoundry/metric-store-release/blob/f5098839f607992caee67ede742e339ebe2979bd/src/pkg/leanstreams/tcpclient.go#L154) used in metric-store and log-store handles this scenario as well.

**Comment by LukeWinikates** [comment]
@oppegard does it make sense to close this issue since the TCP connection methods for the SDK are all deprecated now?

**Comment by oppegard** [comment]
Yep!
